name: THOR
channels:
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.8.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - attrs==23.1.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - easydict==1.11
      - filelock==3.13.1
      - fsspec==2023.12.2
      - idna==3.6
      - imageio==2.33.1
      - jinja2==3.1.2
      - lazy-loader==0.3
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.8.1.78
      - pandas==2.0.3
      - projectaria-tools==1.3.1
      - pyarrow==10.0.1
      - pymeshlab==2023.12
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - rerun-sdk==0.11.0
      - scikit-image==0.21.0
      - scipy==1.10.1
      - sympy==1.12
      - tifffile==2023.7.10
      - torch==2.1.2
      - torchdata==0.7.1
      - torchvision==0.16.2
      - tqdm==4.66.1
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
