python test_THOR_one.py \
 --dataset_name h2o \
 --root /ds-av/public_datasets/h2o/wds/ \
 --checkpoint_folder h2o \
 --checkpoint_id 13 \
 --split val \
 --seq rgb \
 --batch_size 1 \
 --object \
 --photometric \
 --buffer_size 10 \
 --visualize \